### ISSUE TITLE
8 bit PSKs seem to be broken.

### ISSUE THREAD

**Issue by yNosGR** [pdxlocations/MQTT-Connect-for-Meshtastic#62]
When using an 8 bit key other than `AQ==`, it looks like we are throwing some errors and unable to decrypt. Are there any work arounds? In the below paste, I am using `MA==`.
```ynos@slaptop:~/src/Meshtastic-MQTT-Connect$ ./mqtt-connect.py 
Exception in thread Thread-1 (mqtt_thread):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ynos/src/Meshtastic-MQTT-Connect/./mqtt-connect.py", line 1420, in mqtt_thread
    client.loop()
  File "/home/ynos/src/Meshtastic-MQTT-Connect/venv/lib/python3.12/site-packages/paho/mqtt/client.py", line 1635, in loop
    return self._loop(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ynos/src/Meshtastic-MQTT-Connect/venv/lib/python3.12/site-packages/paho/mqtt/client.py", line 1686, in _loop
    rc = self.loop_read()
         ^^^^^^^^^^^^^^^^
  File "/home/ynos/src/Meshtastic-MQTT-Connect/venv/lib/python3.12/site-packages/paho/mqtt/client.py", line 2100, in loop_read
    rc = self._packet_read()
         ^^^^^^^^^^^^^^^^^^^
  File "/home/ynos/src/Meshtastic-MQTT-Connect/venv/lib/python3.12/site-packages/paho/mqtt/client.py", line 3142, in _packet_read
    rc = self._packet_handle()
         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ynos/src/Meshtastic-MQTT-Connect/venv/lib/python3.12/site-packages/paho/mqtt/client.py", line 3814, in _packet_handle
    return self._handle_connack()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ynos/src/Meshtastic-MQTT-Connect/venv/lib/python3.12/site-packages/paho/mqtt/client.py", line 3934, in _handle_connack
    on_connect(
  File "/home/ynos/src/Meshtastic-MQTT-Connect/./mqtt-connect.py", line 1283, in on_connect
    send_node_info(BROADCAST_NUM, want_response=False)
  File "/home/ynos/src/Meshtastic-MQTT-Connect/./mqtt-connect.py", line 753, in send_node_info
    generate_mesh_packet(destination_id, encoded_message)
  File "/home/ynos/src/Meshtastic-MQTT-Connect/./mqtt-connect.py", line 840, in generate_mesh_packet
    mesh_packet.encrypted = encrypt_message(channel, key, mesh_packet, encoded_message)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ynos/src/Meshtastic-MQTT-Connect/./mqtt-connect.py", line 873, in encrypt_message
    cipher = Cipher(algorithms.AES(key_bytes), modes.CTR(nonce), backend=default_backend())
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ynos/src/Meshtastic-MQTT-Connect/venv/lib/python3.12/site-packages/cryptography/hazmat/primitives/ciphers/algorithms.py", line 40, in __init__
    self.key = _verify_key_size(self, key)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ynos/src/Meshtastic-MQTT-Connect/venv/lib/python3.12/site-packages/cryptography/hazmat/primitives/_cipheralgorithm.py", line 55, in _verify_key_size
    raise ValueError(
ValueError: Invalid key size (8) for AES.

**Comment by pdxlocations** [comment]
I believe AES can only be 16 or 32 bit:
<https://meshtastic.org/docs/configuration/radio/channels/#psk>

The script expands 'AQ==' to: "1PG7OiApB1nwvP+rz05pAQ==" which is the actual default key.  AQ== is a nick name.

That said, you could try adding a bunch of '=' at the end of your PSK as padding to make a 16 bit key

**Comment by yNosGR** [comment]
The extra equals thing throws the same error. When I get some free time, I'll poke through and see how they handle 8bit keys in the firmware.
```$ ./mqtt-connect.py 
Exception in thread Thread-1 (mqtt_thread):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ynos/src/Meshtastic-MQTT-Connect/./mqtt-connect.py", line 1420, in mqtt_thread
    client.loop()
  File "/home/ynos/src/Meshtastic-MQTT-Connect/venv/lib/python3.12/site-packages/paho/mqtt/client.py", line 1635, in loop
    return self._loop(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ynos/src/Meshtastic-MQTT-Connect/venv/lib/python3.12/site-packages/paho/mqtt/client.py", line 1686, in _loop
    rc = self.loop_read()
         ^^^^^^^^^^^^^^^^
  File "/home/ynos/src/Meshtastic-MQTT-Connect/venv/lib/python3.12/site-packages/paho/mqtt/client.py", line 2100, in loop_read
    rc = self._packet_read()
         ^^^^^^^^^^^^^^^^^^^
  File "/home/ynos/src/Meshtastic-MQTT-Connect/venv/lib/python3.12/site-packages/paho/mqtt/client.py", line 3142, in _packet_read
    rc = self._packet_handle()
         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ynos/src/Meshtastic-MQTT-Connect/venv/lib/python3.12/site-packages/paho/mqtt/client.py", line 3814, in _packet_handle
    return self._handle_connack()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ynos/src/Meshtastic-MQTT-Connect/venv/lib/python3.12/site-packages/paho/mqtt/client.py", line 3934, in _handle_connack
    on_connect(
  File "/home/ynos/src/Meshtastic-MQTT-Connect/./mqtt-connect.py", line 1283, in on_connect
    send_node_info(BROADCAST_NUM, want_response=False)
  File "/home/ynos/src/Meshtastic-MQTT-Connect/./mqtt-connect.py", line 753, in send_node_info
    generate_mesh_packet(destination_id, encoded_message)
  File "/home/ynos/src/Meshtastic-MQTT-Connect/./mqtt-connect.py", line 840, in generate_mesh_packet
    mesh_packet.encrypted = encrypt_message(channel, key, mesh_packet, encoded_message)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ynos/src/Meshtastic-MQTT-Connect/./mqtt-connect.py", line 873, in encrypt_message
    cipher = Cipher(algorithms.AES(key_bytes), modes.CTR(nonce), backend=default_backend())
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ynos/src/Meshtastic-MQTT-Connect/venv/lib/python3.12/site-packages/cryptography/hazmat/primitives/ciphers/algorithms.py", line 40, in __init__
    self.key = _verify_key_size(self, key)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ynos/src/Meshtastic-MQTT-Connect/venv/lib/python3.12/site-packages/cryptography/hazmat/primitives/_cipheralgorithm.py", line 55, in _verify_key_size
    raise ValueError(
ValueError: Invalid key size (8) for AES.
```

**Comment by pdxlocations** [comment]
I tried "BQ============" and there is no error.
